// Card strings. Hebrew is the default because the data is Hebrew-first; the
// language follows Home Assistant's own setting.

const STRINGS = {
  he: {
    name: "Israel Transit",
    description: "זמני הגעה בזמן אמת לתחבורה הציבורית בישראל",
    scheduled: "לפי לוח זמנים",
    now: "עכשיו",
    minutes: "דק׳",
    minutesLong: "דקות",
    noArrivals: "אין הגעות קרובות",
    noRealtime: "אין כרגע נתוני זמן אמת לתחנה הזו",
    noData: "אין נתונים זמינים לתחנה הזו",
    loading: "טוען…",
    staleData: "אין חיבור כרגע. מוצגים הזמנים האחרונים שהתקבלו.",
    errorUnknownStop: "התחנה לא נמצאה. בדקו את קוד התחנה בהגדרות הכרטיס.",
    errorNotLoaded: "האינטגרציה Israel Transit לא פעילה. בדקו אותה בהגדרות.",
    errorIndex: "לוח הזמנים המקומי עדיין לא מוכן. נסו שוב בעוד כמה דקות.",
    errorConnection: "החיבור ל-Home Assistant התנתק. מתחבר מחדש…",
    errorGeneric: "לא ניתן לטעון כרגע את זמני ההגעה.",
    stop: "תחנה",
    stopDetails: "פרטי התחנה",
    allLines: "כל הקווים בתחנה",
    lineDetails: "פרטי הקו",
    routeStops: "תחנות הקו",
    vehicleHere: "המיקום הנוכחי",
    myStop: "התחנה שלך",
    departedAt: "יצא ב־",
    platform: "רציף",
    delay: "עיכוב",
    delayMinutes: "דק׳ עיכוב",
    onTime: "בזמן",
    operator: "מפעיל",
    destination: "יעד",
    noLines: "לא נמצאו קווים בתחנה הזו",
    noRouteStops: "לא נמצא מסלול לקו הזה",
    close: "סגירה",
    // the map
    vehicleMap: "מיקום הרכב",
    routeLine: "מסלול הקו",
    noVehicleLocation: "המפעיל אינו משדר את מיקום הרכב",
    // editor
    editorStop: "תחנה",
    editorSearch: "חיפוש תחנה לפי שם, עיר, רחוב או קוד",
    editorSearchHelp: 'אפשר לשלב מילים, למשל "כפר סבא ויצמן"',
    editorSearching: "מחפש…",
    editorNoResults: "לא נמצאו תחנות",
    editorLines: "קווים להצגה",
    editorLinesHelp: "בלי בחירה יוצגו כל הקווים בתחנה",
    editorAddLine: "הוספת קו",
    editorAllShown: "כל הקווים בתחנה כבר ברשימה",
    editorMoveUp: "העברה למעלה",
    editorMoveDown: "העברה למטה",
    editorRemove: "הסרה",
    editorTitle: "כותרת מותאמת",
    editorMaxArrivals: "מספר הגעות מרבי",
    editorMaxLines: "מספר קווים מרבי",
    editorMaxLinesHelp: "‏0 = ללא הגבלה",
    editorOrder: "סדר ההצגה",
    editorOrderTime: "לפי זמן ההגעה",
    editorOrderLines: "לפי סדר הקווים שנבחר",
    editorDisplay: "פרטים להצגה",
    editorShowHeader: "כותרת התחנה",
    editorShowCity: "שם העיר",
    editorShowStopCode: "קוד התחנה",
    editorShowDestination: "יעד הקו",
    editorShowOperator: "שם המפעיל",
    editorShowModeIcon: "סמל סוג התחבורה",
    editorShowRealtimeTag: "תווית \"לפי לוח זמנים\"",
    editorShowPlatform: "רציף",
    editorShowDelay: "עיכוב",
    editorShowClock: "שעת הגעה מדויקת",
    editorShowMap: "מפה עם מיקום הרכב",
    editorShowMapHelp: "נפתחת בפרטי הקו, כשהמפעיל משדר מיקום",
    editorChange: "שינוי תחנה",
    editorCancel: "ביטול",
    editorNoStop: "לא נבחרה תחנה",
    errorNoStop: "יש להגדיר קוד תחנה (stop_code)",
    // modes
    mode_0: "רכבת קלה",
    mode_2: "רכבת ישראל",
    mode_3: "אוטובוס",
    mode_5: "רכבלית",
    mode_8: "מונית שירות",
    mode_715: "קו גמיש",
  },
  en: {
    name: "Israel Transit",
    description: "Real-time Israeli public transport arrivals",
    scheduled: "Timetable",
    now: "Now",
    minutes: "min",
    minutesLong: "minutes",
    noArrivals: "No upcoming arrivals",
    noRealtime: "No real-time data for this stop right now",
    noData: "No data is published for this stop",
    loading: "Loading…",
    staleData: "Offline right now. Showing the last times received.",
    errorUnknownStop: "Stop not found. Check the stop code in the card's settings.",
    errorNotLoaded: "The Israel Transit integration is not running. Check it in Settings.",
    errorIndex: "The local timetable is not ready yet. Try again in a few minutes.",
    errorConnection: "Lost the connection to Home Assistant. Reconnecting…",
    errorGeneric: "Could not load arrival times right now.",
    stop: "Stop",
    stopDetails: "Stop details",
    allLines: "All lines at this stop",
    lineDetails: "Line details",
    routeStops: "Stops on this route",
    vehicleHere: "Current position",
    myStop: "Your stop",
    departedAt: "Departed at",
    platform: "Platform",
    delay: "Delay",
    delayMinutes: "min late",
    onTime: "On time",
    operator: "Operator",
    destination: "Destination",
    noLines: "No lines found at this stop",
    noRouteStops: "No route found for this line",
    close: "Close",
    vehicleMap: "Vehicle position",
    routeLine: "Route",
    noVehicleLocation: "The operator is not broadcasting this vehicle's position",
    editorStop: "Stop",
    editorSearch: "Search by stop name, city, street or code",
    editorSearchHelp: 'Words combine, for example "Kfar Saba Weizmann"',
    editorSearching: "Searching…",
    editorNoResults: "No stops found",
    editorLines: "Lines to show",
    editorLinesHelp: "With nothing chosen, every line at the stop is shown",
    editorAddLine: "Add a line",
    editorAllShown: "Every line at this stop is already listed",
    editorMoveUp: "Move up",
    editorMoveDown: "Move down",
    editorRemove: "Remove",
    editorTitle: "Custom title",
    editorMaxArrivals: "Maximum arrivals",
    editorMaxLines: "Maximum lines",
    editorMaxLinesHelp: "0 = no limit",
    editorOrder: "Order",
    editorOrderTime: "By arrival time",
    editorOrderLines: "By the chosen line order",
    editorDisplay: "Details to show",
    editorShowHeader: "Stop header",
    editorShowCity: "City",
    editorShowStopCode: "Stop code",
    editorShowDestination: "Destination",
    editorShowOperator: "Operator name",
    editorShowModeIcon: "Mode icon",
    editorShowRealtimeTag: "Timetable tag",
    editorShowPlatform: "Platform",
    editorShowDelay: "Delay",
    editorShowClock: "Exact arrival time",
    editorShowMap: "Map with the vehicle position",
    editorShowMapHelp: "Opens in the line details, when a position is broadcast",
    editorChange: "Change stop",
    editorCancel: "Cancel",
    editorNoStop: "No stop selected",
    errorNoStop: "You need to define a stop_code",
    mode_0: "Light rail",
    mode_2: "Train",
    mode_3: "Bus",
    mode_5: "Cable car",
    mode_8: "Shared taxi",
    mode_715: "Flexible route",
  },
};

export const languageOf = (hass) =>
  (hass?.locale?.language || hass?.language || "he").toLowerCase().startsWith("he")
    ? "he"
    : "en";

export const localize = (hass, key) => {
  const lang = languageOf(hass);
  return STRINGS[lang][key] ?? STRINGS.en[key] ?? key;
};

export const isRtl = (hass) => languageOf(hass) === "he";
